### ISSUE TITLE
ModuleNotFoundError on importing smat

### ISSUE THREAD

**Issue by mirrdj** [nwithan8/SMAT-API#1]
Hi! I've tried importing the smat API into my jupyter notebook after installing it with pip but ran into the following error (please check image). Any idea what the problem might be?

![Screenshot 2022-12-19 161643](https://user-images.githubusercontent.com/63065598/208458647-9f5f9bb7-a93a-42f9-a758-7a876d80f75e.png)

**Comment by nwithan8** [comment]
I have an idea, will put out a patch.

**Comment by nwithan8** [comment]
Closed as part of a8b83312a224184cc4ddef782914ab2e175d088f and 0.2.0 release
